// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3mYyl8lApwvyL5Y1y3D-YLdKaWPG8pJ4',
    appId: '1:811004230704:web:957b9313198306f91dc1f5',
    messagingSenderId: '811004230704',
    projectId: 'flutter-web-4da88',
    authDomain: 'flutter-web-4da88.firebaseapp.com',
    storageBucket: 'flutter-web-4da88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC23uZIHFEAQY9T3xFMIFbzCsEgGVl1wB8',
    appId: '1:811004230704:android:4f836f4fcb87e80d1dc1f5',
    messagingSenderId: '811004230704',
    projectId: 'flutter-web-4da88',
    storageBucket: 'flutter-web-4da88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnM0x8lR0jkg_C5MmyCEaPaNWk9vYj8xc',
    appId: '1:811004230704:ios:de8a807ba55210501dc1f5',
    messagingSenderId: '811004230704',
    projectId: 'flutter-web-4da88',
    storageBucket: 'flutter-web-4da88.appspot.com',
    iosBundleId: 'com.example.salat',
  );
}
